ProjectCIMS/TuDa.CIMS

- .editorconfig
- STYLEGUIDE.md
Creates a `STYLEGUIDE.md` and a corresponding `.editorconfig`.
> Add a Styleguide and Editorconfig

- docker-compose.yml
- src/TuDa.CIMS.Api/appsettings.Development.json
- src/TuDa.CIMS.Api/appsettings.json
- src/TuDa.CIMS.Web/appsettings.Development.json
- src/TuDa.CIMS.Web/appsettings.json
Corrects the docker-compose and adds a database to the stack.
Additionally add entries to appsettings
> Correct docker-compose

- .github/workflows/ci-build-and-test.yml
- src/TuDa.CIMS.Api/ConfigureServices.cs
- src/TuDa.CIMS.Api/Dockerfile
- src/TuDa.CIMS.Api/Program.cs
- src/TuDa.CIMS.Api/Properties/launchSettings.json
- src/TuDa.CIMS.Api/TuDa.CIMS.Api.csproj
- src/TuDa.CIMS.Shared/TuDa.CIMS.Shared.csproj
- src/TuDa.CIMS.Web/Dockerfile
- src/TuDa.CIMS.Web/TuDa.CIMS.Web.csproj
- test/TuDa.CIMS.Api.Test/TuDa.CIMS.Api.Test.csproj
- test/TuDa.CIMS.Web.Test/TuDa.CIMS.Web.Test.csproj
- test/TuDa.CIMS.Web.Test/UnitTest1.cs
Bumps .Net Version from 8 to 9. Adds `Scalar.AspDotNet` as `Swagger` replacement
> Use .Net 9

- TuDa.CIMS.sln
- src/TuDa.CIMS.Api/TuDa.CIMS.Api.csproj
- src/TuDa.CIMS.Shared/TuDa.CIMS.Shared.csproj
- src/TuDa.CIMS.Web/TuDa.CIMS.Web.csproj
- test/TuDa.CIMS.Api.Test/TuDa.CIMS.Api.Test.csproj
- test/TuDa.CIMS.Shared.Test/TuDa.CIMS.Shared.Test.csproj
- test/TuDa.CIMS.Web.Test/TuDa.CIMS.Web.Test.csproj
- [ErrorOr](https://github.com/amantinband/error-or)
- [FluentValidation](https://github.com/dotnet/efcore)
- [EFCore](https://github.com/dotnet/efcore)
- [Mapster](https://github.com/MapsterMapper/Mapster)
- [QuestPdf](https://github.com/QuestPDF/QuestPDF)
- [MudBlazor](https://github.com/MudBlazor/MudBlazor)
- [Verify](https://github.com/VerifyTests/Verify)
- [FluentAssertions](https://fluentassertions.com/)
- [Moq](https://github.com/moq/moq4)
> Add some usefull libraries

- STYLEGUIDE.md
Correct Blazor Naming after I made a mistake
> Correct Blazor Naming

- STYLEGUIDE.md
Adds some suggestions for HTML formatting
> Add HTML suggestions to the styleguide

- src/TuDa.CIMS.Api/Program.cs
I removed too much in my in #43. This line need to be added again, without it the api wont work
> Fix api not running

- src/TuDa.CIMS.Web/Components/App.razor
- src/TuDa.CIMS.Web/Components/Layout/MainLayout.razor
- src/TuDa.CIMS.Web/Components/_Imports.razor
- src/TuDa.CIMS.Web/Program.cs
This sets up all functionalities of MudBlazor.
I followed the guide on their website https://mudblazor.com/getting-started/installation#manual-install-add-components
> Setup MudBlazor

- infrastructure/TuDa.CIMS.MigrationService/Worker.cs
- src/TuDa.CIMS.Api/Database/CIMSDbContext.cs
- src/TuDa.CIMS.Api/Migrations/20241214152133_FixHazardsPersonsAndPurchases.Designer.cs
- src/TuDa.CIMS.Api/Migrations/20241214152133_FixHazardsPersonsAndPurchases.cs
- src/TuDa.CIMS.Shared/Entities/Hazard.cs
- src/TuDa.CIMS.Shared/Entities/Person.cs
- src/TuDa.CIMS.Shared/Entities/Purchase.cs
- test/TuDa.CIMS.Shared.Test/Faker/PersonFaker.cs
- test/TuDa.CIMS.Shared.Test/Faker/PurchaseFaker.cs
- test/TuDa.CIMS.Shared.Test/Faker/WorkingGroupFaker.cs
This fixes circular relationships of the Entities. They need to be removed to serialize them into json.
> Fix db relations

- src/TuDa.CIMS.Web/Components/PurchaseEntryList.razor
- src/TuDa.CIMS.Web/Components/PurchaseEntryList.razor.cs
> Add `PurchaseEntryList`

- infrastructure/TuDa.CIMS.MigrationService/Worker.cs
- infrastructure/TuDa.CIMS.MigrationService/appsettings.Development.json
- infrastructure/TuDa.CIMS.MigrationService/appsettings.json
- test/TuDa.CIMS.Shared.Test/Faker/BaseEntityFaker.cs
@anngy12 discovered a nasty bug in the migration service. This PR fixes this and adds a switch for Seeding the database
> Fix migration service

- src/TuDa.CIMS.Api/Controllers/AssetItemController.cs
- src/TuDa.CIMS.Api/Controllers/InvoiceController.cs
- src/TuDa.CIMS.Api/Controllers/PurchaseController.cs
- src/TuDa.CIMS.Api/Controllers/WorkingGroupController.cs
- src/TuDa.CIMS.Api/IApiMarker.cs
- src/TuDa.CIMS.Api/Interfaces/IAssetItemRepository.cs
- src/TuDa.CIMS.Api/Program.cs
- src/TuDa.CIMS.Api/Repositories/AssetItemRepository.cs
- src/TuDa.CIMS.Api/Services/InvoiceGenerationService.cs
- src/TuDa.CIMS.Shared/CIMSBaseController.cs
- src/TuDa.CIMS.Shared/Dtos/CreateWorkingGroupDto.cs
- src/TuDa.CIMS.Shared/Dtos/UpdateSubstanceDto.cs
- src/TuDa.CIMS.Shared/Dtos/UpdateWorkingGroupDto.cs
- src/TuDa.CIMS.Shared/TuDa.CIMS.Shared.csproj
- test/TuDa.CIMS.Api.Test/Controllers/AssetItemControllerTest.cs
- test/TuDa.CIMS.Api.Test/Controllers/InvoiceControllerTest.cs
- test/TuDa.CIMS.Api.Test/Controllers/PurchaseControllerTest.cs
- test/TuDa.CIMS.Api.Test/Controllers/WorkingGroupControllerTest.cs
- test/TuDa.CIMS.Api.Test/Integration/AssetItemControllerTest.cs
- test/TuDa.CIMS.Api.Test/Integration/CIMSApiFactory.cs
- test/TuDa.CIMS.Api.Test/Services/InvoiceGenerationServiceTest.cs
- test/TuDa.CIMS.Api.Test/TuDa.CIMS.Api.Test.csproj
- test/TuDa.CIMS.Api.Test/Usings.cs
- test/TuDa.CIMS.Shared.Test/Faker/PurchaseFaker.cs
This setup and adds some integration tests
> Setup testing env

- src/TuDa.CIMS.Api/Controllers/ConsumableTransactionController.cs
- src/TuDa.CIMS.Api/Controllers/PurchaseController.cs
- src/TuDa.CIMS.Api/Interfaces/IAssetItemService.cs
- src/TuDa.CIMS.Api/Interfaces/IConsumableTransactionRepository.cs
- src/TuDa.CIMS.Api/Interfaces/IConsumableTransactionService.cs
- src/TuDa.CIMS.Api/Interfaces/IPurchaseRepository.cs
- src/TuDa.CIMS.Api/Interfaces/IPurchaseService.cs
- src/TuDa.CIMS.Api/Program.cs
- src/TuDa.CIMS.Api/Repositories/ConsumableTransactionRepository.cs
- src/TuDa.CIMS.Api/Repositories/PurchaseRepository.cs
- src/TuDa.CIMS.Api/Services/ConsumableTransactionService.cs
- src/TuDa.CIMS.Api/Services/PurchaseService.cs
- src/TuDa.CIMS.Shared/Dtos/CreateConsumableTransactionDto.cs
- src/TuDa.CIMS.Shared/Dtos/CreatePurchaseEntryDto.cs
- src/TuDa.CIMS.Shared/Entities/Enums/TransactionReasons.cs
- test/TuDa.CIMS.Api.Test/Controllers/ConsumableTransactionTest.cs
- test/TuDa.CIMS.Api.Test/Controllers/PurchaseControllerTest.cs
> Simple consumabletransaction functionality

- src/TuDa.CIMS.Web/Components/Pages/WorkingGroupListPage.razor
- src/TuDa.CIMS.Web/Components/Pages/WorkingGroupListPage.razor.cs
- src/TuDa.CIMS.Web/Components/WorkingGroupList/WorkingGroupPageWorkingGroupList.razor.cs
Not sure if it is the right way to implement it.
> Reload List on Group Creation

- src/TuDa.CIMS.Web/Components/Dashboard/AssetList.razor
The place to add this was harder to find than I expected.
> AssetList Price Sorting

- src/TuDa.CIMS.Web/Components/Pages/InvoicePage.razor
> Improve InvoicePage design

- src/TuDa.CIMS.Api/Migrations/20250124144746_ChangedIntToDoubleAmount.Designer.cs
- src/TuDa.CIMS.Api/Migrations/20250124144746_ChangedIntToDoubleAmount.cs
- src/TuDa.CIMS.Api/Services/ConsumableTransactionService.cs
- src/TuDa.CIMS.Shared/Dtos/CreateConsumableTransactionDto.cs
- src/TuDa.CIMS.Shared/Dtos/CreatePurchaseEntryDto.cs
- src/TuDa.CIMS.Shared/Entities/PurchaseEntry.cs
- src/TuDa.CIMS.Web/Components/Dashboard/Dialogs/AssetItemCreateForm.razor.cs
- src/TuDa.CIMS.Web/Components/Dashboard/Dialogs/AssetItemForm.razor
- src/TuDa.CIMS.Web/Components/Dashboard/Dialogs/ChemicalItemForm.razor
- src/TuDa.CIMS.Web/Components/Dashboard/Dialogs/GasCylinderItemForm.razor
- src/TuDa.CIMS.Web/Components/Pages/ShoppingCartPage.razor.cs
- src/TuDa.CIMS.Web/Components/ShoppingCart/ShoppingCartProductDialog.razor
- src/TuDa.CIMS.Web/Components/ShoppingCart/ShoppingCartProductDialog.razor.cs
- test/TuDa.CIMS.Api.Test/Controllers/PurchaseControllerTest.cs
Its now possible to input decimal numbers, but the error text if an invalid value is put in, is still in english by default.
Don't know how to change the text of this to be honest.
Translation should be fixed through #208 
In addition should it be possible to change the type of the Product to be bought in the `ShoppingCartPage`?
And this might be for another Ticket
> Allow Inputs of Decimal Numbers

- src/TuDa.CIMS.Web/Components/ShoppingCart/ShoppingSearch.razor
- src/TuDa.CIMS.Web/Components/ShoppingCart/ShoppingSearch.razor.cs
Its temporary connected so it will leave some results. Should be changed in #63
> Filter in ShoppingCart

- src/TuDa.CIMS.Web/Components/Dashboard/AssetList.razor
- src/TuDa.CIMS.Web/Components/Dashboard/AssetList.razor.cs
- src/TuDa.CIMS.Web/Program.cs
- src/TuDa.CIMS.Web/TuDa.CIMS.Web.csproj
Its temporary connected so it will leave some results. Should be changed in #63 
CaseInsensitivity not working because server sided data (still working on it) any ideas are welcome.
> Datagrid Filter + MudTranslation

- src/TuDa.CIMS.Api/Documents/InvoiceCoverDocument.cs
- src/TuDa.CIMS.Api/Services/DocumentGenerationService.cs
- src/TuDa.CIMS.Api/appsettings.json
- src/TuDa.CIMS.Shared/Models/AdditionalInvoiceInformation.cs
- src/TuDa.CIMS.Web/Components/Pages/InvoicePage.razor
- src/TuDa.CIMS.Web/Components/Pages/InvoicePage.razor.cs
- test/TuDa.CIMS.Api.Test/Controllers/InvoiceControllerTest.cs
This adapts the `InvoiceDocument` cover page to the new requirements.
🗑️ Removes `Logo`
🗑️ Remove `DueDate` (also from the `FE` page)
♻️  Update `ProjectId`
[invoice_cover.pdf](https://github.com/user-attachments/files/18648215/invoice_cover.pdf)
> Adapt `InvoiceCoverPage` layout

- src/TuDa.CIMS.Web/Components/Dashboard/AssetList.razor
- src/TuDa.CIMS.Web/Components/Dashboard/Dialogs/AssetItemCreateForm.razor
- src/TuDa.CIMS.Web/Components/Dashboard/Dialogs/AssetItemCreateForm.razor.cs
- src/TuDa.CIMS.Web/Components/Dashboard/Dialogs/AssetItemDialog.razor
- src/TuDa.CIMS.Web/Components/Dashboard/Dialogs/AssetItemEditDialog.razor.cs
- src/TuDa.CIMS.Web/Components/Dashboard/Dialogs/AssetItemForm.razor.cs
- src/TuDa.CIMS.Web/Components/Dashboard/Dialogs/ChemicalItemForm.razor.cs
- src/TuDa.CIMS.Web/Components/Dashboard/Dialogs/ConsumableItemForm.razor.cs
- src/TuDa.CIMS.Web/Components/Dashboard/Dialogs/GasCylinderItemForm.razor.cs
- src/TuDa.CIMS.Web/Components/Pages/AssetListPage.razor
- Shop -> Lieferant
- Druckgasflasche -> Technische Gase
- The Errors in the other forms won't appear if they are not selected as the Item to be created.
- After an item is created the Data on the datagrid will refresh without the user having to do it manually
- The Inputs won't get deleted if an error appears
- Deleting an Entry will have a feedback now
> Renaming, Create Item Issue solved, QoL changes

- src/TuDa.CIMS.Web/Components/WorkingGroupPage/WorkingGroupPersonList.razor
- src/TuDa.CIMS.Web/Components/WorkingGroupPage/WorkingGroupPersonList.razor.cs
- src/TuDa.CIMS.Web/Components/WorkingGroupPage/WorkingGroupPurchaseList.razor
- src/TuDa.CIMS.Web/Components/WorkingGroupPage/WorkingGroupPurchaseList.razor.cs
I added the pagination for persons and purchases and the purchases are in descending order.
> Workinggrouppage sorting purchases desc for date and add pagination

- src/TuDa.CIMS.Api/Documents/InvoiceTablesDocument.cs
This does a little redesign of the tables.
➕ New vertical lines to improve visibility
➕ Add sum column
♻️ Decrease padding to get more onto the page
[sum_table.pdf](https://github.com/user-attachments/files/18672975/sum_table.pdf)
> Add sum column to table in `InvoiceDocument`

- src/TuDa.CIMS.Web/Components/Pages/ShoppingCartPage.razor.cs
- src/TuDa.CIMS.Web/Components/ShoppingCart/SignDialog.razor
- src/TuDa.CIMS.Web/Components/ShoppingCart/SignDialog.razor.cs
- src/TuDa.CIMS.Web/Components/_Imports.razor
- src/TuDa.CIMS.Web/TuDa.CIMS.Web.csproj
> Dialog for Signature

- src/TuDa.CIMS.Shared/Models/AdditionalInvoiceInformation.cs
[City and Zip](https://github.com/user-attachments/files/18799520/QuestPDF.Document.1.pdf)
> Add city and zip to InvoiceCoverPage

- src/TuDa.CIMS.Api/Documents/InvoiceTablesDocument.cs
- src/TuDa.CIMS.Shared/Entities/Enums/MeasurementUnits.cs
- src/TuDa.CIMS.Web/Components/Dashboard/AssetList.razor
- src/TuDa.CIMS.Web/Components/ShoppingCart/ShoppingCartPriceView.razor
- src/TuDa.CIMS.Web/Components/ShoppingCart/ShoppingCartSubmitPopupPurchaseList.razor.cs
- test/TuDa.CIMS.Shared.Test/Faker/PurchaseEntryFaker.cs
> IvoiceTable: Use units in amount and price per amount

- src/TuDa.CIMS.Web/Components/Dashboard/AssetList.razor.cs
- src/TuDa.CIMS.Web/Components/Dashboard/Dialogs/AssetItemCreateForm.razor
- src/TuDa.CIMS.Web/Components/Dashboard/Dialogs/AssetItemForm.razor
- src/TuDa.CIMS.Web/Components/Pages/InvoicePage.razor
- src/TuDa.CIMS.Web/Components/ShoppingCart/ShoppingCartSubmitPopupWorkingGroupSelection.razor
- src/TuDa.CIMS.Web/Components/ShoppingCart/ShoppingCartSubmitPopupWorkingGroupSelection.razor.cs
- src/TuDa.CIMS.Web/Components/ShoppingCart/ShoppingSearch.razor
- src/TuDa.CIMS.Web/Components/ShoppingCart/ShoppingSearch.razor.cs
> New Note Input + Renaming + Clear Shopping Search + Default Sorting

- src/TuDa.CIMS.Web/Components/Dashboard/Dialogs/AssetItemEditForm.razor
- src/TuDa.CIMS.Web/Components/Dashboard/Dialogs/AssetItemEditForm.razor.cs
- src/TuDa.CIMS.Web/Components/ShoppingCart/ShoppingCartProductDialog.razor
- src/TuDa.CIMS.Web/Components/ShoppingCart/ShoppingCartProductDialog.razor.cs
> Consumable Statistics in Edit Form

- infrastructure/TuDa.CIMS.AppHost/Program.cs
This adds `PgWeb` an easy-to-use web interface for Postgres
> Add PgWeb to Aspire

- src/TuDa.CIMS.Web/Components/PurchaseInformation/PurchaseInformationPopup.razor
- src/TuDa.CIMS.Web/Components/PurchaseInformation/PurchaseInformationPopup.razor.cs
- src/TuDa.CIMS.Web/Components/WorkingGroupPage/WorkingGroupPurchaseList.razor.cs
This just converts the `DateTime` to local time before displaying
> DateTime to LocalTime before displaying

- src/TuDa.CIMS.Api/Repositories/AssetItemRepository.cs
- src/TuDa.CIMS.Api/Services/ConsumableService.cs
- src/TuDa.CIMS.Shared/Dtos/CreateConsumableDto.cs
- src/TuDa.CIMS.Web/Components/Dashboard/Dialogs/AssetItemCreateForm.razor
- src/TuDa.CIMS.Web/Components/Dashboard/Dialogs/AssetItemCreateForm.razor.cs
- src/TuDa.CIMS.Web/Components/Dashboard/Dialogs/ConsumableItemCreateForm.razor
- src/TuDa.CIMS.Web/Components/Dashboard/Dialogs/ConsumableItemForm.razor
- src/TuDa.CIMS.Web/Components/Dashboard/Dialogs/ConsumableItemForm.razor.cs
- src/TuDa.CIMS.Web/Components/Pages/AssetListPage.razor.cs
- test/TuDa.CIMS.Api.Test/Controllers/AssetItemControllerTest.cs
- test/TuDa.CIMS.Api.Test/Controllers/ConsumableControllerTest.cs
- test/TuDa.CIMS.Shared.Test/Faker/ConsumableTransactionFaker.cs
I added a Popup that requires the user to decide either the amount should be tracked as bought in this year or not.
I don't know if I'm 100% sure that's the best option. Any opinions on that?
> Add possibility to create consumable without creating an transaction

- src/TuDa.CIMS.Api/Interfaces/IConsumableTransactionRepository.cs
- src/TuDa.CIMS.Api/Repositories/ConsumableTransactionRepository.cs
- src/TuDa.CIMS.Api/Services/PurchaseInvalidationService.cs
- test/TuDa.CIMS.Api.Test/Controllers/PurchaseControllerInvalidationTest.cs
When testing #354 I recognized, that when trying to update the amount of an Item in invalidation, that is almost empty, it would return an error, that the Amount is too low.
I investigated and found, that my calculations in the update function for the invalidation were wrong and I corrected them in this PR
> Correctly update Consumables when invalidate Purchase

- .github/workflows/cd-build-and-release.yml
I did a syntax mistake and fixed it.
Without this, no docker files can be created.
> Fix release pipeline

- src/TuDa.CIMS.Web/Components/Pages/WorkingGroupListPage.razor.cs
- src/TuDa.CIMS.Web/Components/WorkingGroupPage/WorkingGroupInfoPopOut.razor
- src/TuDa.CIMS.Web/Components/WorkingGroupPage/WorkingGroupInfoPopOut.razor.cs
- src/TuDa.CIMS.Web/Components/WorkingGroupPage/WorkingGroupPersonList.razor.cs
This pull request includes several changes to improve dependency injection, update method calls, and enhance error handling in the `TuDa.CIMS.Web` project. The most important changes include replacing property injection with constructor injection, updating method calls for dialog interactions, and adding error handling with snackbar notifications.
* [`src/TuDa.CIMS.Web/Components/Pages/WorkingGroupListPage.razor.cs`](diffhunk://#diff-ca771446c6bc923effc31456ea31acd94ea7f3d9c2199fc1262cabc5421f2acaL12-R27): Replaced property injection with constructor injection for `IDialogService`, `IWorkingGroupApi`, and `ISnackbar`.
* [`src/TuDa.CIMS.Web/Components/Pages/WorkingGroupListPage.razor.cs`](diffhunk://#diff-ca771446c6bc923effc31456ea31acd94ea7f3d9c2199fc1262cabc5421f2acaL37-R77): Updated …
> Improve Dependency Injection, Dialog Handling, and Error Feedback

- src/TuDa.CIMS.Web/Components/WorkingGroupPage/WorkingGroupInfoPopOut.razor.cs
The initialization for `ProfessorInfo` and `WorkingGroup` were missing but necessary because these entities are mandatory.
Otherwise it throws a `NullPointerEcxeption` when you try to open the dialog.
> Fix the NullPointerException in the `WorkingGroupHeader`

- src/TuDa.CIMS.Web/Components/WorkingGroupPage/WorkingGroupPurchaseList.razor
Like described in #321, this was removed, unfortunately. This will add the functionality again
> Reenable invalidation indicator

- README.md
> Fix Callout in Readme

- src/TuDa.CIMS.Web/Components/Pages/WorkingGroupPage.razor
- src/TuDa.CIMS.Web/Components/Pages/WorkingGroupPage.razor.cs
- src/TuDa.CIMS.Web/Components/WorkingGroupPage/WorkingGroupHeader.razor
- src/TuDa.CIMS.Web/Components/WorkingGroupPage/WorkingGroupHeader.razor.cs
- src/TuDa.CIMS.Web/Components/WorkingGroupPage/WorkingGroupInfoPopOut.razor
- src/TuDa.CIMS.Web/Components/WorkingGroupPage/WorkingGroupInfoPopOut.razor.cs
- src/TuDa.CIMS.Web/Components/WorkingGroupPage/WorkingGroupInvoiceButton.razor
- src/TuDa.CIMS.Web/Components/WorkingGroupPage/WorkingGroupInvoiceButton.razor.cs
- src/TuDa.CIMS.Web/Components/WorkingGroupPage/WorkingGroupPersonList.razor
- src/TuDa.CIMS.Web/Components/WorkingGroupPage/WorkingGroupPersonList.razor.cs
- src/TuDa.CIMS.Web/Components/WorkingGroupPage/WorkingGroupPurchaseList.razor
- src/TuDa.CIMS.Web/Components/WorkingGroupPage/WorkingGroupPurchaseList.razor.cs
- src/TuDa.CIMS.Web/Extensions/DialogServiceExtension.cs
This pull request includes several changes to the `WorkingGroupPage` and its related components to improve data handling and user interface. The most important changes include moving the `WorkingGroup` retrieval to the page, updating the components to use `WorkingGroupResponseDto`, and refactoring the `WorkingGroupHeader` and `WorkingGroupInfoPopOut` components.
> Refactor WorkingGroupPage
